# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('md_file', models.FileField(blank=True, upload_to=b'')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='last edited')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('html_file', models.FileField(blank=True, upload_to=b'')),
                ('category', models.CharField(choices=[('nc', 'No Category'), ('acg', 'Anime & Manga & Novel & Game'), ('programming', 'Programming')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.BlogPost')),
            ],
        ),
    ]
