# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0002_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_test', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': '\u535a\u5ba2'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('nc', 'No Category'), ('programming', 'Programming'), ('nt', 'Note')], max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='html_file',
            field=models.FileField(upload_to='xx'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='md_file',
            field=models.FileField(blank=True, upload_to='xx'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(upload_to='xx'),
        ),
    ]
