# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170318_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='html_file',
            field=models.FileField(upload_to='xx'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='md_file',
            field=models.FileField(blank=True, upload_to='xx'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(upload_to='xx'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(blank=True, max_length=1200),
        ),
    ]
