# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170318_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
